### ISSUE TITLE
Auto-pairing in other paired devices doesn't work (CSR USB dongle)

### ISSUE THREAD

**Issue by richterdeveloper** [ViGEm/BthPS3#14]
Since I installed BthPS3, I need to re-pairing my 8bitdo controller to the CSR USB Bluetooth dongle (I need to do all process in the Windows Device Configuration panel every time after disconnect the controller). I don't know if this is an issue with my CSR dongle or is an issue in BthPS3.

Thanks!!

**Comment by nefarius** [comment]
[See this piece of documentation](https://vigem.org/projects/BthPS3/Driver-Configuration-Utility-Explained/#filter-driver-settings), I'm afraid this is a side-effect of the overall design (I highly recommend to read all the provided docs carefully) since the filter probably interferes with the controller of yours. Try turning it off (explained in the docs) and if that doesn't help, I'm afraid the only solution is to not use the software in conjunction with your controller in question.

**Comment by richterdeveloper** [comment]
> 
> 
> [See this piece of documentation](https://vigem.org/projects/BthPS3/Driver-Configuration-Utility-Explained/#filter-driver-settings), I'm afraid this is a side-effect of the overall design (I highly recommend to read all the provided docs carefully) since the filter probably interferes with the controller of yours. Try turning it off (explained in the docs) and if that doesn't help, I'm afraid the only solution is to not use the software in conjunction with your controller in question.

This solution is working flawless. Thanks!!
