### ISSUE TITLE
Have you been thinking of making a version of this for Android?

### ISSUE THREAD

**Issue by SecularSteve** [ViGEm/BthPS3#3]
While Android 8.0 (and above) Phones have Out-Of-The-Box support for DS3/Sixaxis controllers, you can only pair them by wire (or maybe even a dongle, but I never heard of anyone trying it).

The only way to do it on Androids is to root your device first, and then getting the Master Key in order to pair it wirelessly to the device using a very shady app from Google Play.

But that's just a suggestion, I just think it would be nice to be able to do that without a root.

**Comment by nefarius** [comment]
Problem with the SIXAXIS "pairing" is, that it's a non-standard-compliant custom Sony way to do it. You need to send a custom crafted USB packet to the controller to tell it its new master radio MAC address. Possibly also the link key to properly encrypt the channels, but that is speculation I don't know on top of my head.

So unless Android also has a modified USB/HID stack that can deal with the SIXAXIS pairing quirks I'm afraid that root is the only way. I assume the app you mentioned is able to send said USB packet by somehow using a lower level API that only system/root processes can use. Without the apps sources it's just speculation though.

So since the Bluetooth side of things is "working" on Android, this is a different issue entirely and I'm afraid I can't really add much value without just emulating what mentioned app does and providing the sources for it.

I haven't really followed history on how SIXAXIS support evolved in Android so I can't really offer any great insights.
